# -*- coding: utf-8 -*-
"""sentiment analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Dl0U90JcXPKdfpLMiiCuLF-hZs-Bjc9
"""

print("hello")
print('hello')

# strings in python
 a = "hello"
print(a)

# Mount Google Drive (optional)
from google.colab import drive
drive.mount('/content/drive')

# Install OpenAI library using pip
!pip install openai

import openai
print("OpenAI library is installed successfully!")

pip install --upgrade openai

import requests

# Set your OpenAI API key
openai_api_key = "sk-proj-KJIdBLph5JCk8f7ZTXFjT3BlbkFJTaTle8IPqS4ogTna1oGd"

# API endpoint URL
url = "https://api.openai.com/v1/chat/completions"

# Request headers
headers = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {openai_api_key}"
}

# Request payload
payload = {
    "model": "gpt-3.5-turbo-16k",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Hello!"
        }
    ]
}

# Send POST request
response = requests.post(url, headers=headers, json=payload)

# Print response content
print(response.json())

import openai

# Set your OpenAI API key securely
openai.api_key = "sk-proj-KJIdBLph5JCk8f7ZTXFjT3BlbkFJTaTle8IPqS4ogTna1oGd"

def sentiment_analysis(text):
    messages = [
        {
            "role": "system",
            "content": """You are trained to analyze and detect the sentiment of given text.
                          If you are unsure, you can say 'not sure' and recommend the user to review manually."""
        },
        {
            "role": "user",
            "content": f"Analyze the following text and determine if the sentiment is positive or negative. "
                       f"Return answer in a single word as either positive or negative: {text}"
        }
    ]

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages,
        max_tokens=1,
        n=1,
        stop=None,
        temperature=0
    )

    response_text = response['choices'][0]['message']['content'].strip().lower()
    return response_text

# Calling the function
input_text = 'I love Pakistan'
response = sentiment_analysis(input_text)
print(input_text, ': the sentiment is', response)